@extends('layouts/layout-ns')

@section('title')
    nextShop::Términos y Condiciones.
@endsection

@section('main')
    
  <div class="container bg-light ">

    <div class="row">

      <div class="col-lg-3">

        <h4 class="my-4">Términos y Condiciones</h4>

    <!-- Barra de Navegación Izquierda-->

        <div class="list-group navbarIzq">
            <a class="list-group-item " href="#">Publicidad</a>
            <a class="list-group-item" href="#">Publicidad</a>
            <a class="list-group-item " href="#">Publicidad</a>
        </div>

      </div>

    <!-- Formulario Login-->

    <div class="col-lg-9">

        <div class="card card-outline-secondary my-4">
          <div class="card-header">
            Términos y Condiciones. nextShop.
          </div>
          <div class="card-body">

            <div class="form-login">
<p>Bienvenidos a <a href="http://127.0.0.1:8000">www.nextshop.com</a> (el “Sitio”) de NextShop S.A.I.C.e.I. (“nextShop”). A continuación se incluyen las condiciones generales de utilización de los servicios ofrecidos en el Sitio (el “Servicio” y las “Condiciones de Uso” respectivamente) que regirán los derechos y obligaciones entre los usuarios (los “Usuarios” y/o el “Usuario”) y nextShop. nextShop recomienda especialmente guardar una copia impresa de las Condiciones de Uso al ingresar en el Sitio, el Usuario declara saber, conocer y aceptar las presentes Condiciones de Uso. Las Condiciones de Uso, así como sus modificaciones, estarán vigentes en forma inmediata a su publicación en el Sitio. La utilización del Sitio implica el conocimiento y la aceptación plena por parte del Usuario de las Condiciones de Uso. En caso de no aceptar en las Condiciones de Uso o cualquier cambio o modificación de las mismas no deberá continuar utilizando el Sitio.
Naturaleza del Servicio y destino del Sitio. El Sitio ha sido programado para que constituya un medio virtual para el acceso de los Usuarios a las góndolas de la tienda de nextShop del área de su domicilio.
Usuarios que pueden utilizar los Servicios del Sitio. Los Servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los Servicios las personas que no tengan esa capacidad, los menores de edad o quien registre como Usuario una persona jurídica, deberá tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de estas Condiciones de Uso.
Uso de los Servicios. El Usuario, ya sea registrado o “invitado”, declara que la información que brindará al remitir el pedido de registración será precisa, correcta y actual comprometiéndose a informar en forma inmediata y fehaciente respecto de cualquier cambio siendo a su vez enteramente responsable frente a nextShop por los daños y perjuicios que el incumplimiento de dicha obligación pudiere acarrearle incluyendo pero no limitándose a costos de ubicación física del Usuario, costos de intimaciones y citaciones, etc.
<br><br>      
El Usuario acepta que utilizará los Servicios exclusivamente con los fines estipulados en (a) las Condiciones de Uso y (b) cualquier norma o regulación aplicable ya sea de índole municipal, provincial o nacional incluyendo pero no limitándose a leyes, decretos, ordenanzas, resoluciones, directivas, etc. El Usuario se compromete a no divulgar su contraseña a terceros que no estuvieren autorizados por el Usuario para acceder a los Servicios del Sitio.
Ámbito de aplicación. Estas Condiciones de Uso son aplicables a cualquiera de todas las ventas de productos y/o servicios a ser realizadas por nextShop dentro de la República Argentina. La realización de un pedido supone la aceptación expresa del Usuario a las presentes Condiciones de Uso.
Al aceptar estas Condiciones de Uso, registrándose como Usuario o ingresando como “invitado”, usted declara bajo juramento y certifica tener 18 años de edad o más. Si usted no está de acuerdo (o no puede cumplir) con cualquiera de las reglas de las Condiciones de Uso, no utilice el Sitio. Toda la información proporcionada al momento de operar con el Sitio debe ser precisa y veraz. Proporcionar información inexacta o falsa constituye una violación grave de estas Condiciones de Uso. Confirmando su pedido en el final del proceso de una operación, el Usuario acuerda aceptar los artículos adquiridos y pagar su precio, perfeccionando con nextShop un contrato de compra-venta de mercadería.
<br><br>      
      <b>Referencias a terceros.</b> Las referencias en el Sitio a nombres, marcas, productos o servicios de terceros, o vínculos de hipertexto a sitios Web o información de terceros se proveen únicamente como una comodidad para el Usuario y de ninguna forma constituyen o implican respaldo, patrocinio o recomendación por nextShop respecto de la tercera parte, su información, productos o servicios. nextShop no tiene control de las prácticas o políticas de esos terceros, ni del contenido de los sitios Web de cualesquiera terceros y no hace ninguna declaración o promesa con respecto a productos o servicios de terceros, o respecto del contenido o la exactitud de cualquier material alojado en dichos sitios de terceros. Si el Usuario decide navegar o seguir un vínculo hacia cualquiera de tales sitios Web de terceros, lo hace enteramente bajo su propio riesgo y responsabilidad.
Orden de compra correspondiente a cada pedido. El Usuario deberá formular su pedido de la misma forma en que llena su carrito en nuestras tiendas, o sea recorriendo virtualmente las góndolas de la tienda, escogiendo las mercaderías que desea comprar e indicando respecto de cada ítem la cantidad que desea comprar.
El procedimiento del Sitio le da oportunidad de añadir o quitar ítems del pedido, de anularlo por completo y de revisarlo. Pueden existir mínimos o máximos en la cantidad, volumen o precio de los ítems incluidos en una orden de compra. Todos los precios publicados en el sitio son precios exclusivos para la compra online de los productos y podrán diferir o ser idénticos a los precios publicados en el resto de las sucursales según el caso.
<br><br>      
      <b>Aceptación de pedidos.</b> Por favor, tenga en cuenta que puede ocurrir que luego de aprobado por el Usuario un pedido, por distintas razones nextShop no esté en condiciones de aceptarlo total o parcialmente y deba por ello cancelar o excluir del mismo algunos ítems pedidos por el Usuario. Algunas situaciones pueden dar lugar a que algunos ítems de su pedido sean excluidos del mismo, ya sea debido a limitaciones en las cantidades disponibles para la compra; faltantes de mercadería en la respectiva góndola; falta de autorización a la operación por parte de la entidad emisora o administradora de su tarjeta de crédito; inexactitudes o errores en el producto o información; o problemas identificados por el departamento de prevención de fraude de crédito y de precios. Para su seguridad, le informamos que eventualmente podemos requerirle información o realizar verificaciones adicionales antes de aceptar cualquier pedido. Si se cancela todo o parte de su pedido o si se necesita información adicional para aceptar su pedido, nos pondremos en contacto con usted. En todos los casos que deban realizarse una modificación o cancelación parcial de su pedido, el Usuario tendrá siempre derecho a cancelar la totalidad del mismo. nextShop, en uso de sus facultades, se reserva el derecho de anular definitivamente cualquier operación luego de la constatación de los datos ingresados, en cuyo caso se le comunicará al usuario la decisión. Todas las compras efectuadas estarán sujetas al stock informado, debido a las demoras propias de las actualizaciones del sistema, es posible que el mismo le permita realizar una compra que luego deba ser anulada por falta de stock. En ese caso le será informado en el e-mail confirmatorio.
<br><br>      
      <b>Forma de entrega y pago.</b> Una vez que un pedido haya quedado confirmado y el importe de su factura aprobado, salvo que existan inconvenientes excepcionales para la aceptación del pedido por parte de nextShop, que le serán debidamente comunicados, recibirá un correo electrónico en el plazo de las 24 horas confirmando que la operación ha sido exitosa. Si el Usuario no recibe tal notificación vía correo electrónico deberá contactarse con el Centro de Atención al Cliente nextShop a fin de constatar que no hubo errores de registro al ingresar la casilla de correo.
Actualmente el Usuario dispone dos métodos de entrega de la mercadería: Envío a domicilio. Retira en Sucursal. Cuando el método de entrega seleccionado sea “Envío a domicilio”, la compra deberá ser recepcionada preferentemente por el titular del método de pago utilizado, o bien por una persona autorizada que cumpla con las Condiciones de Uso del Sitio. El Usuario podrá designar una persona autorizada a recibir la mercadería y/o servicio adquirido en el domicilio de entrega indicado únicamente para la modalidad “Envío a domicilio”. Al hacer la entrega del Producto, se le solicitará el DNI a fin de corroborar que sea el Titular o el Autorizado a recibirlo, adicionalmente, &nbsp;y con la sola finalidad de evitar posibles fraudes, el transportista/empleado podrá tomar con su Smartphone una fotografía del DNI presentado.
En el caso de operaciones de “Retira en Sucursal” deberá seguir los pasos que se detallan a continuación: Elija la sucursal de retiro. Recomendamos la más cercana a su domicilio. Recibirá, dentro de las siguientes setenta y dos (72) horas, un e-mail de confirmación indicando que ya puede retirar el pedido. Una vez que reciba el e-mail de confirmación de su compra y habilitación para retirar el/los producto/s adquirido/s, podrá dirigirse, dentro de los treinta (30) días corridos, a la sucursal que haya seleccionado, con el comprobante de la compra efectuada impreso o exhibido en su dispositivo móvil, y retirar su pedido. Cuando se presente en la sucursal, deberá dirigirse al sector de Cajas, donde deberá presentar: DNI y tarjeta con la que realizó el pago (ambos en original). La entrega sólo se hará efectiva al titular del medio de pago, sin excepción. Mail de confirmación de compra, que incluye el número de pedido:
NOTA: para operaciones de sábados, domingos y feriados de 17 a 22 Hs. los pedidos podrán ser retirados el día siguiente, una vez que reciba el e-mail de confirmación de su compra.
En cualquiera de las modalidades de entrega, se le exhibirá al Usuario el estado de la mercadería y los accesorios que vienen con esta debiendo el Usuario (o la persona autorizada por este, en su caso) verificar que la mercadería entregada corresponde a los artículos incluidos en el pedido y en el remito que se le presentará en el acto de entrega. La firma del remito y/o la del comprobante de pago implicará declaración de conformidad con la mercadería entregada, sin perjuicio de los derechos que le pudieren corresponder en caso de que la misma resultara por algún motivo defectuosa.
Costo del servicio de entrega a domicilio y casos de imposibilidad de entrega. El servicio de entrega a domicilio se encuentra habilitado en determinadas localidades del país, las cuales podrán ser consultadas durante el proceso de compra online, momento en el cual el Usuario procederá a seleccionar según su conveniencia. El servicio de entrega a domicilio se efectuará dentro de un margen mínimo de 72 horas (que podrá extenderse hasta 15 días hábiles en función de la ubicación del domicilio de entrega informado por el Usuario) y tendrá un costo, que aparecerá expresado y diferenciado en la etapa del proceso de llenado del carrito previa a la emisión de su pedido. Dicho costo se añadirá al de las mercaderías detalladas en la correspondiente factura electrónica. La confirmación del pedido y el pago realizado on line, implicarán la aceptación del Usuario del costo del servicio de entrega a domicilio y consecuentemente también el monto total de la correspondiente factura electrónica que recibirá en el e-mail registrado en el pedido. En todos los casos, la fecha de entrega será comunicada al Usuario en el e-mail que registró en el pedido.
En caso de que en el día de entrega no encontremos en el domicilio un titular habilitado para la recepción (sea el Usuario y/o a la persona autorizada por este en su caso), se volverá a coordinar otra fecha de entrega para lo cual el cliente puede comunicarse al Centro de Atención al Cliente, 0810-444-7025.
En caso de que por dificultades imprevistas nextShop no pudiere cumplir con la entrega a domicilio, según los plazos por zona geográfica, se le comunicará en no más de cinco (5) días hábiles y se pactará la entrega de la mercadería para un nuevo día y horario a convenir, sin que se devengue por ello ningún cargo adicional para el Usuario. Cualquier plazo pactado de entrega informado es estimado, aclarándosele que pueden verificarse demoras en la entrega del producto derivadas de un sinnúmero de variables ajenas al control de nextShop.
<br><br>
      <b>Productos en estado de PRUEBA.</b>
Para mejorar su experiencia en el Sitio, nextShop podrá realizar pruebas con productos que no estarán disponibles para la venta en las condiciones publicadas.  Estos productos estarán consignados como “Producto en estado de PRUEBA. Precio irrisorio, no valido para la compra”. En ningún caso se podrá efectivizar la compra de uno de estos productos ya que, aún si el Sitio permitiera realizar los pasos necesarios, el intento de compra no superaría el estado de aprobación posterior.
<br><br>
      <b>Medios de Pago.</b> El Sitio cuenta con los siguientes medios de pago válidos para compras online: - Visa, - Master Card, - American Express, - Cabal, - Dinners, - Naranja, - Shopping.
Es derecho de nextShop la inclusión, exclusión o suspensión de cualquier medio de pago.
<br><br>      
Tipo de comprobantes a emitir. En venta on line, por el momento sólo se emitirán facturas electrónicas a Consumidor Final (Comprobantes tipo “B”). La misma será remitida al e-mail informado en el pedido, sin excepción. En caso de no recibirla, contactarse al Centro de Atención al Cliente al teléfono 0810-444-7025 para corroborar un posible error en la carga del e-mail en el pedido.
<br><br>      
      <b>Operatividad y Seguridad del Sitio.</b> El Usuario se compromete a no acceder ni a intentar acceder al Sitio ni usar de ninguno de los Servicios por ningún otro medio que no sea la interfaz provista por nextShop.
Asimismo, se compromete a no involucrarse en ninguna actividad que interfiera o que interrumpa o que tuviere entidad suficiente para interferir o interrumpir la prestación de los Servicios del Sitio o los servidores y redes conectados al mismo.
Está prohibido a los Usuarios violar, vulnerar y/o de cualquier forma afectar el normal uso y la seguridad del Sitio, incluyendo, pero sin limitarse a: 
a)	acceder a datos que no se destinan a ese Usuario o ingresar a una computadora o a una cuenta a los cuales no esté el Usuario autorizado para acceder;
b)	tratar de sondear, analizar o probar la vulnerabilidad de un sistema o una red o romper medidas de seguridad o autenticación sin la debida autorización;
c)	intentar interferir con el servicio a cualquier Usuario, computadora o red, incluyendo, sin que la siguiente enumeración implique limitación, cuando se lo haga a través de medios de envío de un virus al Sitio, sobrecarga, inundación ("flooding") envío masivo de mensajes no solicitados ("spamming") envío de códigos destructivos ("mailbombing") o anulación de instrucciones del software ("crashing”). Las violaciones de la seguridad del sistema o de la red pueden dar lugar a responsabilidad civil o penal. nextShop investigará sucesos que puedan implicar esas violaciones y puede involucrar a cooperar con las autoridades encargadas de hacer cumplir la ley para enjuiciar a los usuarios que participen en esas violaciones. Usted acepta no utilizar ningún dispositivo, software o rutina para interferir o intentar interferir con el buen funcionamiento de este Sitio o cualquier actividad que se lleve a cabo en este Sitio. Usted acepta, además, no utilizar ni intentar utilizar cualquier motor, software, herramienta, agente u otro dispositivo o mecanismo (incluyendo sin limitación los navegadores, arañas (spyders), robots y avatares) para navegar o buscar en este Sitio, que no sean los motores de búsqueda y agentes de búsqueda que nextShop hace disponibles en este Sitio y diferentes de los navegadores Web de terceros disponibles para el público en general (por ejemplo, Mozilla Firefox, Internet Explorer, Opera, Google Chrome, entre otros).
El Usuario y/o el navegante ocasional del Sitio aceptan y reconocen expresamente que cualquier hecho, acto u omisión vinculadas con lo referido anteriormente y que tengan entidad para afectar la seguridad y/o el normal desarrollo del Sitio tienen entidad suficiente para causar a nextShop considerables daños y perjuicios incluyendo pero no limitándose a lucro cesante por caída y/o merma en las ventas, afectación de sus marcas, imagen comercial, pérdida de clientela, etc.
<br><br>      
      <b>Contraseñas y seguridad de la cuenta del Usuario.</b> Por medio de la aceptación de las Condiciones de Uso el Usuario, reconoce y acepta que es el único responsable de mantener la confidencialidad de su contraseña. En consecuencia, el Usuario acepta que será el único responsable ante nextShop de todas y cada una de las actividades que se efectúen en su cuenta en el Sitio. El Usuario deberá notificar de inmediato a nextShop cualquier uso no autorizado de su contraseña o cuenta de que tenga conocimiento, a través del Sitio. Esta notificación deberá efectuarse a través del Sitio y, adicionalmente, remitiendo una nota al domicilio de nextShop debiendo especificar en ambos casos y en detalle toda la información con la que cuente respecto del uso no autorizado de su contraseña.
<br><br>      
      <b>Datos Personales.</b> Al registrarse como Usuario de este Sitio, suministrará información que, a criterio de nextShop, resulta necesaria para brindar un mejor servicio. Los datos personales del Usuario se toman con los fines de cumplir con el giro comercial de nextShop, realizar acciones de marketing y publicidad. PARA EL CASO QUE EL USUARIO DECIDA PROPORCIONAR SUS DATOS, SE CONSIENTE EXPRESAMENTE QUE nextShop PODRÁ UTILIZARLOS CON FINES OPERATIVOS DEL SISTEMA DE COMERCIO ELECTRÓNICO EN ESTE SITIO Y/O EN OTROS SITIOS WEB PERTENECIENTES A nextShop E INCLUSO PARA HACERLE LLEGAR POR DISTINTOS MEDIOS OFERTAS DE MERCADERÍAS O SERVICIOS, ANUNCIOS DE PROMOCIONES, O PUBLICIDAD. Al comunicarnos sus datos personales por medio de su registro en el Sitio, USTED PRESTA EL CONSENTIMIENTO PREVISTO POR LA LEY ARGENTINA Nº 25.236, INCLUYENDO LA POSIBILIDAD DE CESIÓN PREVISTA EN SU ART. 11 QUE USTED PODRÁ REVOCAR EN CUALQUIER MOMENTO SIMPLEMENTE SOLICITÁNDOLO VÍA CORREO ELECTRÓNICO Y/O MEDIANTE CUALQUIER OTRA FORMA QUE PUEDA SER FÁCILMENTE ACREDITABLE. El Sitio tiene una estricta política de privacidad y protección de los datos generados por la actividad en línea de sus usuarios. nextShop no entregará ningún tipo de datos personales ni de información individualizada sobre ninguno de sus Usuarios a ningún tercero, sea en forma gratuita u onerosa, incluyendo cualquier dato relacionado con la identidad de sus usuarios, sus hábitos, costumbres, ámbitos de pertenencia, hábitos de consumo, etc. USTED SE NOTIFICA Y AUTORIZA A nextShop PARA ANALIZAR LA INFORMACIÓN RELACIONADA CON SUS USUARIOS COMO GRUPO, Y BASÁNDOSE EN DICHOS ANÁLISIS OFRECER, INDIVIDUALMENTE O EN CONJUNTO CON TERCEROS, BIENES Y SERVICIOS A SUS USUARIOS. nextShop ESTÁ AUTORIZADO A COMPARTIR CON TERCEROS LA INFORMACIÓN DESPERSONALIZADA RELACIONADA CON SUS USUARIOS.
El Usuario, en cuanto titular de los datos personales, tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido al artículo 14, inciso 3 de la Ley n° 25.326. nextShop aconseja a sus clientes que mantengan actualizados sus datos. De esta forma recibirán en forma periódica ofertas y promociones diseñadas a medida de sus necesidades. Si desea actualizar sus datos dirijase a: datospersonales@garbarino.com.ar o mediante el ejercicio del derecho de acceso previsto por el art. 14 de la Ley 25.326.
nextShop no solicita datos de sus clientes, ni en forma telefónica ni a través del correo electrónico, más que en los casos estipulados en el punto “Aceptación de Pedidos”. De existir un contacto, tiene como finalidad la realización de alguna encuesta de satisfacción o comunicar alguna promoción o beneficio especial. nextShop se encuentra inscripto en el Registro Nacional de la Dirección Nacional de Protección de Datos Personales, dependiente del Ministerio de Justicia y Derechos humanos tal como lo establece la ley. Si Ud. desea conocer más en profundidad sobre este tema haga click aquí o en la siguiente dirección: http://www.jus.gov.ar/dnpdp
La Dirección Nacional De Protección De Datos Personales, Órgano de Control de la Ley n° 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales permite.
Si Ud. desea conocer más en profundidad sobre este tema haga click aquí o en la siguiente dirección: <a href="http://www.jus.gov.ar/dnpdp">www.jus.gov.ar/dnpdp</a>
<br><br>      
      <b>Precios.</b> Dado que el propósito del Sitio es permitir a los Usuarios realizar compras online, sin concurrir personalmente a las sucursales, los precios de cada artículo deberán ser los que el Usuario observaría en caso de recorrer las góndolas de dicha sucursal el día del armado del pedido. No obstante que nextShop se esfuerza por proporcionar información precisa sobre esos precios, pueden ocurrir errores. En el caso de que un artículo figure en las listas del Sitio a un precio incorrecto debido a un error, nextShop tendrá el derecho, de corregir la orden facturando el precio vigente al momento del armado del pedido en la tienda o bien, de anular el pedido reintegrando al Usuario los importes abonados. En este caso, se dará aviso del error al Usuario, y con él la posibilidad de cancelar o modificar la compra del producto facturado u ofrecido de forma incorrecta.
<br><br>      
      <b>Promociones.</b> Las promociones que se ofrezcan en el Sitio no son necesariamente las mismas que ofrezcan otros canales de venta utilizados por nextShop, tales como sucursales físicas, Venta Telefónica, catálogos u otros, a menos que se señale expresamente en este Sitio o en la publicidad que se realice para cada promoción. En los casos que el Sitio contenga promociones que consistan en la entrega gratuita o rebajada de un producto por la compra de otro, entonces el despacho del bien que se entregue gratuitamente o a precio rebajado, se hará en el mismo lugar en el cual se despacha el producto comprado. No se podrá participar en estas promociones sin adquirir conjuntamente todos los productos comprendidos en ellas.
Salvo indicación en contrario o aprobación por parte de nextShop las promociones no son acumulativas unas con otras.
<br><br>      
      <b>Descripciones e imágenes de la mercadería.</b> nextShop intenta ser lo más preciso posible en sus descripciones de productos. Sin embargo, es posible que las descripciones de los productos u otros contenidos de este Sitio no sean exactos o contengan errores. Sin perjuicio de lo dispuesto en el art. 34 de la ley 24.240, en caso de existencia de error entre la imagen publicitada de un producto y el producto adquirido, el Usuario tendrá derecho a cancelar el pedido hasta 15 días corridos de que hubiere sido entregado sin recibir observación alguna por parte del Usuario. En caso de cancelación del pedido una vez recibido el producto el Usuario fundándose en inexactitudes en la descripción o imágenes del producto, el Usuario deberá reintegrar el mismo en perfecto estado, conjuntamente con todo su empaque original y todos sus accesorios.
La información sobre características de los productos, a la que se accede a través de este Sitio se obtiene de afirmaciones hechas por el fabricante de cada producto. Por favor tenga en cuenta que, en ocasiones los fabricantes pueden alterar sus empaques y etiquetas, de manera que el verdadero embalaje del producto y materiales adjuntos pueden contener información diferente de la que se muestra en el Sitio. nextShop recomienda especialmente que adicionalmente a la información presentada en línea lea las etiquetas, advertencias e instrucciones antes de adquirir, utilizar o en cualquier forma consumir un producto. Para obtener información adicional acerca de un producto, por favor póngase en contacto con el fabricante, distribuidor o importador.
<br><br>      
      <b>Publicidad.</b> nextShop se reserva el derecho de incluir en el Sitio anuncios publicitarios, que se identificarán a los efectos de ser distinguirlos de las informaciones acerca de descripción y precio de los artículos ofrecidos. Esas inclusiones publicitarias se dirigen únicamente a llamar la atención de los Usuarios sobre determinadas ofertas y no reemplazan las descripciones de los productos hechas en el Sitio correspondiente al artículo, que el Usuario deberá utilizar para evaluar y realizar su compra online.
<br><br>      
      <b>Límites de cantidad y ventas a distribuidores.</b> nextShop se reserva el derecho, cuando tenga razones que así lo justifiquen, de limitar la cantidad de artículos comprados por persona, por hogar o por pedido. Estas restricciones pueden ser aplicables a los pedidos realizados por la misma cuenta o la misma tarjeta de crédito y también a los pedidos que utilizan la misma dirección de facturación y/o de entrega.
<br><br>      
      <b>Derechos de autor y marcas registradas.</b> A menos que se indique lo contrario, los derechos de autor, marcas comerciales, presentación comercial (trade dress) y/u otros derechos de propiedad intelectual sobre todo y cualquier contenido del Sitio son de propiedad, o controlados o licenciados, de nextShop y están protegidos por las leyes Argentinas y tratados internacionales sobre propiedad intelectual. La compilación (es decir, la colección, secuencia, estructura, organización y montaje) de todo el contenido de este Sitio es propiedad exclusiva de nextShop y también está protegida por las leyes Argentinas y tratados internacionales sobre propiedad intelectual.
nextShop y/o sus proveedores y/o licenciantes se reservan expresamente todos los derechos de propiedad intelectual sobre todos los textos, productos, procesos, tecnología, contenido y otros materiales que aparecen en este Sitio. El acceso a este Sitio no confiere a nadie ninguna licencia respecto de cualquier derecho de propiedad intelectual de nextShop o de cualquier tercero, salvo que conste con una autorización expresa de parte de nextShop.
Los nombres y logotipos de nextShop y todos los productos relacionados y nombres de servicio, marcas de diseño y eslóganes son las marcas comerciales o marcas de servicio de nextShop. Todas las demás marcas son propiedad de sus respectivos registrantes. No se concede ninguna licencia de marca registrada o marca de servicio en relación con los materiales contenidos en este Sitio. El acceso a este Sitio no autoriza a nadie a utilizar cualquier nombre, logotipo o marca de cualquier manera.
<br><br>
      <b>Prohibiciones al Usuario y sus responsabilidades.</b> Está terminantemente prohibido al Usuario explotar de cualquier forma las informaciones adquiridas por medio del Sitio. No podrá reproducir los textos o imágenes de los anuncios para otros fines que los de su propio recordatorio personal.
El Usuario se compromete a tomar a su cargo cualquier responsabilidad contractual o extracontractual que derive de actos como Usuario del Sitio y acepta mantener indemne a nextShop, respecto de y contra cualquier reclamo por parte de terceros, derivado o relacionado con el uso inadecuado del Sitio o por la violación de las presentes Condiciones de Uso y sus respectivas modificaciones, o que surja de dicho uso y/o a causa de algún comentario publicado por el Usuario en el Sitio.
<br><br>      
      <b>Terminación.</b> Estas Condiciones de Uso implican un contrato que entrará en vigor tan pronto el Usuario acepte las Condiciones de Uso y/o use los servicios del Sitio y permanecerán vigentes hasta que el presente contrato sea cancelado sea por el Usuario o por nextShop. El Usuario puede rescindir este contrato en cualquier momento, siempre que lo haga para el futuro evitando el uso de este Sitio y/o siendo Usuario Registrado, renunciando a su registro siguiendo el procedimiento especialmente previsto para ello. nextShop también puede rescindir este contrato en cualquier momento siendo válida la notificación de tal rescisión a los domicilios reales o electrónicos que el Usuario tuviere registrados en el Sitio. Asimismo nextShop podrá cancelar sin previo aviso la condición de Usuario, y en consecuencia denegar el acceso a los Servicios del Sitio o a comprar por esta vía, si el Usuario no cumpliera con cualquier término o disposición de las presentes Condiciones de Uso. Esta cláusula se aplicará sea o no el Usuario un navegante registrado. nextShop podrá en cualquier momento, temporal o permanentemente dar de baja este Sitio.
<br><br>      
      <b>Modificaciones en las Condiciones de Uso.</b> En caso de que estas Condiciones de Uso sean modificadas, tales modificaciones serán publicadas en el Sitio, obrando en él la versión vigente al momento del inicio de cada sesión. Toda vez que por tratarse de un sitio Web abierto a los clientes en general, nextShop carece de posibilidad de notificarle particularmente a cada uno de ellos, salvo mediante la publicación en el propio Sitio, por lo que el Usuario se compromete a verificar en forma las Condiciones de Uso con cualquier uso que haga del mismo, entendiéndose que al iniciar cada sesión acepta las que estén vigentes y publicadas en ese momento en la forma y con los efectos establecidos en las presentes Condiciones de Uso.
<br><br>      
      <b>General. </b>Las Condiciones de Uso representan el acuerdo completo entre las partes y sustituyen a todos los acuerdos anteriores que pudieran existir entre ellas. Los títulos utilizados en estas Condiciones de Uso son sólo con fines de referencia y en ninguna manera definen o limitan el alcance de la disposición que titulan. Si cualquier disposición de las mismas se considerara inaplicable por cualquier razón, tal disposición deberá reformarse sólo en la medida necesaria para hacerla exigible y las demás condiciones del presente Acuerdo permanecerán en pleno vigor y efecto. La inacción de nextShop con respecto a un incumplimiento de este acuerdo por el Usuario o por otros no constituye una renuncia y no limitará los derechos de nextShop con respecto a dicho incumplimiento o infracciones posteriores.
<br><br>      
      <b>Ley aplicable, resolución de controversias, medidas procesales y notificaciones.</b> Este contrato será gobernado por y se interpretará según la legislación vigente en la República Argentina. Cualquier conflicto relacionado con este contrato o con el uso que el Usuario haga de este Sitio será resuelto por los tribunales ordinarios competentes según la legislación vigente y aplicable a la relación de consumo existente entre las partes. En caso de que dicha legislación no defina una competencia específica, será competente la justicia nacional ordinaria en asuntos comerciales con asiento en la Ciudad Autónoma de Buenos Aires, siendo aplicable esta disposición aunque el Usuario estuviera realmente domiciliado fuera de los límites de la Ciudad Autónoma de Buenos Aires o de la República Argentina, por entenderse que este lugar ha sido el lugar de celebración del presente contrato. Salvo que lo contrario haya sido acordado previamente y por escrito firmado entre el Usuario y nextShop, todas las notificaciones que se hagan a los usuarios en relación a las presentes Condiciones de Uso se publicarán en el Sitio y tendrán efecto desde la fecha de su publicación. Las notificaciones que el Usuario quiera dirigir a nextShop deberán ser dirigidas a Bolívar 874, Ciudad Autónoma de Buenos Aires donde queda constituido el domicilio.
  nextShop. Todos los derechos reservados.</p>

            </div>
            
          </div>
        </div>
        <!-- /.card -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>

@endsection